Repository LNP-BP/LNPBPs, pull requests merged in 2021-05, with the labels that each got.

#107 correct typos, readability, symbols
  lnpbp-0001.md
Labels: [DBC], enhancement

#68 LNPBP-2 rewrite & finalization
  lnpbp-0002.md
Labels: *security*, [DBC], enhancement

#106 Typos and clarification
  lnpbp-0002.md
Labels: [DBC], enhancement

#110 [trivial] Fix reference implementation link URL
  lnpbp-0003.md
Labels: [DBC]

#109 LNPBP-1 pubkey serialization spec
  lnpbp-0001.md
Labels: [DBC]
